
-- enum types
CREATE TYPE USER_ROLE AS ENUM (
    'OWNER'
    'ADMIN',
    'MEMBER'
);

CREATE TYPE MEMBERSHIP_ROLE AS ENUM (
    'OWNER',
    'MANAGER',
    'STAFF'
);

CREATE TYPE LIBARRY_STATUS AS ENUM (
    'ACTIVE',
    'SUSPENDED',
    'ARCHIVED'
);

CREATE TYPE BOOK_STATUS AS ENUM (
    'AVAILABLE',
    'BORROWED',
    'RESERVED',
    'LOST',
    'DAMAGED',
    'MAINTENANCE'
);

CREATE TYPE TRANSACTION_STATUS AS ENUM (
    'LEND',
    'RETURN',
    'SALE',
    'LOSS'
);

-- users
CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    FIRST_NAME VARCHAR (100) NOT NULL,
    MIDDLE_NAME VARCHAR (100),
    LAST_NAME VARCHAR (100) NOT NULL,
    EMAIL VARCHAR (255) UNIQUE NOT NULL,
    PHONE VARCHAR (30),
    PASSWORD_HASH TEXT,
    ROLE USER_ROLE NOT NULL DEFAULT 'MEMBER',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE INDEX IDX_USERS_EMAIL ON USERS (EMAIL);

CREATE INDEX IDX_USERS_ROLE ON USERS (ROLE);

-- libraries (organizations)
CREATE TABLE LIBRARIES (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    NAME VARCHAR (255) UNIQUE NOT NULL,
    SLUG VARCHAR (200) UNIQUE NOT NULL,
    DESCRIPTION TEXT,
    STATUS LIBARRY_STATUS NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY UUID NOT NULL REFERENCES USERS (ID),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW (),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW ()
);

-- memberships
-- a user can belong to many libraries
-- a library can have many users
CREATE TABLE LIBRARY_MEMBERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    LIBRARY_ID UUID NOT NULL REFERENCES LIBRARIES (ID) ON DELETE CASCADE,
    USER_ID UUID NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    ROLE MEMBERSHIP_ROLE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW (),
    UNIQUE (LIBRARY_ID, USER_ID)
);

-- categories
CREATE TABLE CATEGORIES (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    LIBRARY_ID UUID NOT NULL REFERENCES LIBRARIES (ID) ON DELETE CASCADE,
    NAME VARCHAR (100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW (),
    UNIQUE (LIBRARY_ID, NAME)
);

-- books
CREATE TABLE BOOKS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    TITLE VARCHAR (500) NOT NULL,
    ISBN VARCHAR (20) UNIQUE,
    DESCRIPTION TEXT,
    PUBLICATION_YEAR INT,
    PUBLISHER_ID UUID,
    LANGUAGE VARCHAR (50),
    PAGE_COUNT INT,
    COVER_IMAGE_URL TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_BOOK_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS (ID) ON DELETE SET NULL
);

CREATE INDEX IDX_BOOKS_TITLE ON BOOKS (TITLE);

CREATE INDEX IDX_BOOKS_ISBN ON BOOKS (ISBN);


-- borrowers
CREATE TABLE BORROWERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    LIBRARY_ID UUID NOT NULL REFERENCES LIBRARIES (ID) ON DELETE CASCADE,
    NAME VARCHAR (255) NOT NULL,
    PHONE VARCHAR (50),
    EMAIL VARCHAR (255),
    ADDRESS TEXT,
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT NOW ()
);

-- transactions
CREATE TABLE BOOK_TRANSACTIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    LIBRARY_ID UUID NOT NULL REFERENCES LIBRARIES (ID) ON DELETE CASCADE,
    BOOK_ID UUID NOT NULL REFERENCES BOOKS (ID),
    BORROWER_ID UUID NOT NULL REFERENCES BORROWERS (ID),
    TRANSACTION_DATE TIMESTAMP NOT NULL DEFAULT NOW (),
    DUE_DATE DATE,
    RETURNED_AT TIMESTAMP,
    AMOUNT NUMERIC (12,2),
    REMARKS TEXT,
    PERFOMED_BY UUID REFERENCES USERS (ID)
);

-- audit logs
CREATE TABLE AUDIT_LOGS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    LIBRARY_ID UUID NOT NULL REFERENCES LIBRARIES (ID),
    USER_ID UUID NOT NULL REFERENCES USERS (ID),
    ACTION VARCHAR (100) NOT NULL,
    ENTITY VARCHAR (100),
    ENTITY_ID UUID,
    OLD_DATA JSONB,
    NEW_DAT JSONB,
    CREATED_AT TIMESTAMP DEFAULT NOW (),
);