
-- enum types
CREATE TYPE USER_ROLE AS ENUM (
    'ADMIN',
    'MEMBER'
);

CREATE TYPE BOOK_STATUS AS ENUM (
    'AVAILABLE',
    'BORROWED',
    'RESERVED',
    'LOST',
    'DAMAGED',
    'MAINTENANCE'
);

CREATE TYPE LOAN_STATUS AS ENUM (
    'ACTIVE',
    'RETURNED',
    'OVERDUE',
    'LOST'
);

CREATE TYPE PAYMENT_STATUS AS ENUM (
    'PENDING',
    'PAID',
    'WAIVED'
);

-- users
CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    FIRST_NAME VARCHAR (100) NOT NULL,
    MIDDLE_NAME VARCHAR (100),
    LAST_NAME VARCHAR (100) NOT NULL,
    EMAIL VARCHAR (255) UNIQUE NOT NULL,
    PHONE VARCHAR (30),
    PASSWORD_HASH TEXT,
    ROLE USER_ROLE NOT NULL DEFAULT 'MEMBER',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE INDEX IDX_USERS_EMAIL ON USERS (EMAIL);

CREATE INDEX IDX_USERS_ROLE ON USERS (ROLE);

-- authors
CREATE TABLE AUTHORS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    FIRST_NAME VARCHAR (100) NOT NULL,
    MIDDLE_NAME VARCHAR (100),
    LAST_NAME VARCHAR (100) NOT NULL,
    BIOGRAPHY TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_AUTHORS_NAME ON AUTHORS (LAST_NAME);

-- publishers
CREATE TABLE PUBLISHERS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    NAME VARCHAR (255) UNIQUE NOT NULL,
    ADDRESS TEXT,
    WEBSITE VARCHAR (255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- categories
CREATE TABLE CATEGORIES (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    NAME VARCHAR (100) UNIQUE NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- books
CREATE TABLE BOOKS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    TITLE VARCHAR (500) NOT NULL,
    ISBN VARCHAR (20) UNIQUE,
    DESCRIPTION TEXT,
    PUBLICATION_YEAR INT,
    PUBLISHER_ID UUID,
    LANGUAGE VARCHAR (50),
    PAGE_COUNT INT,
    COVER_IMAGE_URL TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_BOOK_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS (ID) ON DELETE SET NULL
);

CREATE INDEX IDX_BOOKS_TITLE ON BOOKS (TITLE);

CREATE INDEX IDX_BOOKS_ISBN ON BOOKS (ISBN);

-- book authors (many to many)
CREATE TABLE BOOK_AUTHORS (
    BOOK_ID UUID NOT NULL,
    AUTHOR_ID UUID NOT NULL,
    PRIMARY KEY (BOOK_ID, AUTHOR_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE CASCADE
);