CREATE TABLE BOOKS (
    ID UUID,
    TITLE VARCHAR (255) NOT NULL,
    AUTHOR VARCHAR (255) NOT NULL,
    ISBN VARCHAR (13) UNIQUE,
    PUBLISHER VARCHAR (255),
    PUBLICATION_DATE DATE,
    PAGES INT,
    LANGUAGE VARCHAR (50),
    QUANTITY INT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);